### ISSUE TITLE
[Epic] Cross-database `date` macro

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#10075]
This epic comprises the changes across dbt Labs repos necessary to implement a cross-database `date` macro  as described in https://github.com/dbt-labs/dbt-adapters/issues/192.

### Implementation

There is no equivalent function specified in ISO/IEC 9075 (the SQL standard), so there is not a natural adapter-agnostic implementation from them.

However, many database vendors support a `to_date` function with syntax similar to the following:
```sql
to_date('{{ iso_8601_formatted_date }}', 'YYYY-MM-DD')
```

So we can utilize that as the base implementation and adapters can customize as-needed.

### Utility

This function is also generally useful anytime someone wants to generate SQL to create an scalar `DATE` value by supplying an explicit year, month, day combo.

An expected use is supplying a start and end date to `dbt.date_spine`.

For example, https://github.com/dbt-labs/dbt-core/issues/8825 describes how we'd like to automatically create a `metricflow_time_spine` model if the project defines any semantic objects, and that relies upon being able to do a cross-database `dbt.date_spine` given an explicit start and end date.

```[tasklist]
### dbt-adapters
- [ ] https://github.com/dbt-labs/dbt-adapters/issues/192
- [ ] https://github.com/dbt-labs/dbt-adapters/pull/191
```

```[tasklist]
### dbt-postgres
- [ ] https://github.com/dbt-labs/dbt-postgres/issues/82
- [ ] https://github.com/dbt-labs/dbt-postgres/pull/81
```

```[tasklist]
### dbt-redshift
- [ ] https://github.com/dbt-labs/dbt-redshift/issues/808
- [ ] https://github.com/dbt-labs/dbt-redshift/pull/806
```

```[tasklist]
### dbt-snowflake
- [ ] https://github.com/dbt-labs/dbt-snowflake/issues/1013
- [ ] https://github.com/dbt-labs/dbt-snowflake/pull/1011
```

```[tasklist]
### dbt-bigquery
- [ ] https://github.com/dbt-labs/dbt-bigquery/issues/1221
- [ ] https://github.com/dbt-labs/dbt-bigquery/pull/1219
```

```[tasklist]
### dbt-spark
- [ ] https://github.com/dbt-labs/dbt-spark/issues/1031
- [ ] https://github.com/dbt-labs/dbt-spark/pull/1030
```

```[tasklist]
### Documentation
- [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/5427
- [ ] Include in migration guide for adapter maintainers
```
