### ISSUE TITLE
[Epic] Multi-project collaboration: one year in

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#10125]
Bugs and quality-of-life improvements, collected and prioritized based on feedback from dbt Cloud customers and community members, now that "dbt Mesh" has been out in the world for 6+ months — and thousands are using its constructs in production.

```[tasklist]
### P0 - must
- [ ] https://github.com/dbt-labs/dbt-core/issues/10116
- [ ] https://github.com/dbt-labs/dbt-core/issues/8987
- [ ] https://github.com/dbt-labs/dbt-core/issues/7442
```

```[tasklist]
### P0 - should
- [ ] https://github.com/dbt-labs/dbt-core/issues/9340
- [ ] https://github.com/dbt-labs/dbt-core/issues/9339
- [ ] https://github.com/dbt-labs/dbt-core/issues/8266
- [ ] https://github.com/dbt-labs/dbt-core/issues/8062
```

```[tasklist]
### P2 - could
- [ ] https://github.com/dbt-labs/dbt-core/issues/8951
- [ ] https://github.com/dbt-labs/dbt-core/issues/8986
- [ ] https://github.com/dbt-labs/dbt-core/issues/8248
- [ ] https://github.com/dbt-labs/dbt-core/issues/5410
```

```[tasklist]
### revisit, refine, prioritize
- [ ] https://github.com/dbt-labs/dbt-core/issues/7432
- [ ] https://github.com/dbt-labs/dbt-core/issues/7759
```

**Comment by jaklan** [comment]
#5410 should be definitely a must - as described in the issue, it's completely breaking the monorepo usage of `dbt`
