### ISSUE TITLE
[Epic] Snapshots as a First Class Citizen

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#10151]
An epic to improve the usability and accuracy of snapshots.

```[tasklist]
### P0 - must
- [ ] https://github.com/dbt-labs/dbt-core/issues/4000
- [ ] https://github.com/dbt-labs/dbt-core/issues/10326
- [ ] https://github.com/dbt-labs/dbt-core/issues/10325
- [ ] https://github.com/dbt-labs/dbt-core/issues/10301
- [ ] https://github.com/dbt-labs/dbt-core/issues/10234
- [ ] https://github.com/dbt-labs/dbt-core/issues/10185
- [ ] https://github.com/dbt-labs/dbt-core/issues/10246
- [ ] https://github.com/dbt-labs/dbt-core/issues/10187
- [ ] https://github.com/dbt-labs/dbt-core/issues/10235
- [ ] https://github.com/dbt-labs/dbt-core/issues/10921
```

```[tasklist]
### P1 - should
- [ ] https://github.com/dbt-labs/dbt-core/issues/9992
- [ ] https://github.com/dbt-labs/dbt-core/issues/10372
- [ ] https://github.com/dbt-labs/dbt-core/issues/10236
- [ ] https://github.com/dbt-labs/dbt-core/issues/7867
- [ ] https://github.com/dbt-labs/dbt-core/issues/8207
- [ ] https://github.com/dbt-labs/dbt-core/issues/7869
- [ ] https://github.com/dbt-labs/dbt-core/issues/10300
```

```[tasklist]
### p2 - could
- [ ] https://github.com/dbt-labs/dbt-core/issues/10438
- [ ] https://github.com/dbt-labs/dbt-core/issues/7138
- [ ] https://github.com/dbt-labs/dbt-core/issues/10320
```

```[tasklist]
### revisit, refine, prioritize
- [ ] https://github.com/dbt-labs/dbt-core/issues/3878
- [ ] https://github.com/dbt-labs/dbt-core/issues/4661
- [ ] https://github.com/dbt-labs/dbt-core/issues/2848
- [ ] https://github.com/dbt-labs/dbt-adapters/issues/82
- [ ] https://github.com/dbt-labs/dbt-core/issues/8885
```

### Discussions
[Problems & (Potential) Solutions for Snapshots](https://github.com/dbt-labs/dbt-core/discussions/7018)
[Toggling values when snapshotting a table with a key violation](https://github.com/dbt-labs/dbt-core/issues/6089)

**Comment by danielefrigo** [comment]
another interesting customization could be the ability to configure the value for `dbt_valid_to` then opening a new record.
dbt default is null, but in many cases I found the need to have a far away timestamp (e.g. '2999-12-31').

**Comment by graciegoheen** [comment]
@danielefrigo Yes! This is something we'd like to do - issue here -> https://github.com/dbt-labs/dbt-core/issues/10187

**Comment by jeremyyeo** [comment]
Snapshots currently don't support contracts. Would be great have snapshots support contracts/constraints just as models do.

**Comment by graciegoheen** [comment]
Thanks @jeremyyeo - would you be down to open up a new issue for that feature request?
