### ISSUE TITLE
Milestone: 1.0

### ISSUE THREAD

**Issue by drewbanin** [dbt-labs/dbt-core#2277]
This issue exists to track features, fixes, and changes required for dbt to hit version 1.0. All of the issues enumerated here should be labeled with the `1.0.0` issue label. When all of the issues attached here have been completed, we can cut a 1.0.0 release of dbt.

### Changes
- [x] Reconcile the SourceConfig (https://github.com/fishtown-analytics/dbt/issues/2273)
- [ ] Add blocks for all resources
  - [ ] ~Model blocks (https://github.com/fishtown-analytics/dbt/issues/184)~
  - [ ] ~Custom data test blocks (https://github.com/fishtown-analytics/dbt/issues/2274)~
  - [x] Schema test definition blocks (https://github.com/fishtown-analytics/dbt/issues/1173)
  - [ ] ~Analysis blocks (https://github.com/fishtown-analytics/dbt/issues/2275)~
  - [ ] ~Seed blocks (https://github.com/fishtown-analytics/dbt/issues/2276)~
- [x] Rationalize test selection (#2203)
- [ ] ~Make materializations return complete/compiled SQL output~
- [x] Reconcile paths (#1607, #2659)
- [x] Move plugins out of dbt core and into separate repos (#3361)
... + more issues to come ....

**Comment by clrcrl** [comment]
Suggested additions from when I've been writing docs:
- [ ] Rationalize use of `tags` config / property (e.g. sometimes it's a config, sometimes it's in a `schema.yml` file which I'm calling a property henceforth).
- [ ] Make data and schema tests configurable from `dbt_project.yml`. Lack of support for configs in the `dbt_project.yml` makes it impossible to "turn off" a test in a package (I think?)
    - Currently you can't configure a data test from `dbt_project.yml`, though it can be from a `{{ config() }}` block.
    - You can't do either for a schema test. 
- [ ] Make return type of custom schema tests and data tests consistent (number 0 versus 0 records)
- [ ] Allow data tests to be documented (everything else can, why not these?)

**Comment by jtcohen6** [comment]
Closing now that `v1.0.0rc1` is out in the world. We got to most of this, not all. If an idea is good enough, I trust it will have its time in the sun post-v1.
