### ISSUE TITLE
[Tracking] v0.21.1RC1 release 

### ISSUE THREAD

**Issue by leahwicz** [dbt-labs/dbt-core#4054]
### Release Core
- [x] [Engineering] Verify all necessary changes exist on the release branch
- [x] [Engineering] Follow [dbt-release workflow](https://www.notion.so/dbtlabs/Releasing-b97c5ea9a02949e79e81db3566bbc8ef#03ff37da697d4d8ba63d24fae1bfa817) 
- ~[Product] Update migration guide (next.docs.getdbt.com)~

### Release Cloud
- [ ] [Engineering] Create a platform issue to update dbt Cloud and verify it is completed. [Example issue](https://github.com/dbt-labs/dbt-cloud/issues/3481)
- [ ] [Engineering] Determine if schemas have changed. If so, generate new schemas and push to schemas.getdbt.com

### Announce
- ~[Product] Publish discourse~
- [x] [Product] Announce in dbt Slack — thanks Joel!!

### Post-release
- [x] [Engineering] [Bump plugin versions](https://www.notion.so/dbtlabs/Releasing-b97c5ea9a02949e79e81db3566bbc8ef#f01854e8da3641179fbcbe505bdf515c) (dbt-spark + dbt-presto), add compatibility as needed
   - [x]  [Spark](https://github.com/dbt-labs/dbt-spark) 
   - [x]  [Presto](https://github.com/dbt-labs/dbt-presto)
- [ ] [Engineering] Create a platform issue to update dbt-spark versions to dbt Cloud. [Example issue](https://github.com/dbt-labs/dbt-cloud/issues/3481)
- [ ] ~[Product] Release new version of dbt-utils with new dbt version compatibility. If there are breaking changes requiring a minor version, plan upgrades of other packages that depend on dbt-utils.~
- [ ] [Engineering] Create an epic for the final release

**Comment by jtcohen6** [comment]
@leahwicz At this point, what do you think about:
- cutting `v0.21.1rc2` (to include the fix in #4197/#4207)
- getting that into dbt Cloud ASAP
- giving folks a week to test it out
- cutting the final v0.21.1 release next week

**Comment by swanderz** [comment]
> @leahwicz At this point, what do you think about:
> 
>     * cutting `v0.21.1rc2` (to include the fix in [Add get_where_subquery to test namespace #4197](https://github.com/dbt-labs/dbt-core/pull/4197)/[[Backport] #4197 #4207](https://github.com/dbt-labs/dbt-core/pull/4207))
> 
>     * getting that into dbt Cloud ASAP
> 
>     * giving folks a week to test it out
> 
>     * cutting the final v0.21.1 release next week

Just adding here that the `0.21.0` releases of dbt-sqlserver and dbt-synapse are blocked until dbt-core `0.21.1` is released due to #4084. Looking forward to next week's release!
