### ISSUE TITLE
Structured Logging Cleanup

### ISSUE THREAD

**Issue by nathaniel-may** [dbt-labs/dbt-core#4441]
### Describe the Feature

Now that the necessary items for 1.0.0 have been completed in #4260,  we can continue working on these items.

### Tasks
- [ ] revisit and cleanup #4336 #4370
- [ ] fine tune look and feel
    - respect user configs around ~color +~ printer width #4373 
    - ~handle duplication a la `[ warn  ] | [WARNING]:`~ (less relevant now that log level are excluded from CLI)
    - handle text formatting RE [this example](https://github.com/dbt-labs/dbt-core/issues/4260#issuecomment-971943351).
- [ ] inspect every event to determine its destination(s)
- [ ] improve message wording (will break tests and that's ok. should rely on new codes from above instead)
- [ ] find a better alternative to `extra.run_state` and update the current tests that rely on that field. Tests are currently commented out.
- [ ] remove testing logs via #3977 
- [ ] better rpc backdoor that's not an env var dbt-rpc#63
- [ ] generated documentation from event dataclasses
- [x] automated breaking change detection. (comparable static version schemas)
- [ ] json validation schema (better testing coverage, and potentially helpful with auto-detecting breaking changes)
- [ ] move deprecation message logic into the events module. Move [this entry point](https://github.com/dbt-labs/dbt-core/blob/9d73304c1a39a4c4a4caca8b44645169b4ea9c4e/core/dbt/exceptions.py#L996) higher up the list of functions.
