### ISSUE TITLE
[CT-288] Pytest Conversion Tracking

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#4788]
#  Pytest Integration Test Conversion Progress

As you grab test directories to convert, add the associated issue to the list so everyone knows you're working on it.  Check it off once complete. We separated the tests that are only related to dbt-core and adapter tests. But not all tests are reviewd. Please look at the test when converting and see where it best belongs to.

### Integration Tests
- [x] 001_simple_copy_test -  #4690 
- [x] 002_varchar_widening_tests - #4731
- [x] 003_simple_reference_test -  #4690 
- [x] #4806
- [x] #5174
- [x] 007_graph_selection_tests -  #4729 
- [x] 008_schema_tests_tests #4826
- [x] 010_permission_tests #4826 
- [x] 011_invalid_model_tests #5143
- [x] 012_deprecation_tests - #5030 
- [x] 013_context_var_tests - #5188 
- [x] 015_cli_invocation_tests - #5959
- [x] 017_runtime_materialization_tests - #5205
- [x] #6576
- [x] #6005
- [x] #6468
- [x] #6100
- [x] #6002
- [x] #6093
- [x] 028_cli_vars_tests - #5136
- [x] 031_thread_count_tests - #5769
- [x] #6467
- [x] #6573
- [x] #6574
- [x] 039_config_tests - #5120
- [x] #6010
- [x] #6575
- [x]  #6121
- [x] #6466
- [X] 047_dbt_ls_tests - #5049
- [x] 053_custom_materialization_tests - #5205
- [x] 055_ref_override_tests #6600
- [x] #6606
- [x] 058_fail_fast_tests #4826
- [x] 059_source_overrides_tests - converting as part of #4889 
- [x] 061_use_colors_tests - #5771
- [x] 065_postgres_index_tests - #5770
- [x] 066_test_selection_tests #4826
- [x] #5768
- [x] 069_build_tests #5128
- [x] #5730
- [x] #5729
- [x] #5728
- [x] #5727
- [x] 075_metrics_tests - #4572
- [x] #6638

### Tests that appeared in adapter repos

Exit criteria:
- Reviewed to see if they still need to be running in adapter repos (testing adapter-specific behavior)
- Converted, added to `dbt-tests-adapter`, and running successfully (via inheritance) in all relevant adapter repos

List:
- [x] 005_simple_seed_tests - #5060  -- normal functional test
- [x] 009_data_tests_tests - #5139 
- [x] #5496
- [x] #5665
- [x] #5666
- [x] #5731
- [x] #5732
- [x] #5829
- [x] 029_docs_generate_tests #5035
- [x] #5830
- [x] #5831
- [x] #5951
- [x] 042_sources_tests - converting as part of #4889 
- [x] #5950
- [x] #6272
- [x] #6403
- [x] 054_adapter_methods_tests #4939
- [x] #6404
- [x] #6273
- [x] #6613
- [x] #6274
- [x] #6623
- [x] 067_store_test_failures_tests
- [x] #6330 
- [x] 076 _incremental_unique_id

### Final cleanup
- [ ] #6862
