### ISSUE TITLE
[CT-1581] [Epic] dbt-core as a library: first steps

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-core#6356]
The scope of this epic is adding new functionality to `dbt-core`, on top of the foundations being laid in #5527, that will enable its top-level commands to be invoked via Python—and to make that a delightful experience.

In addition, we'll be tracking lower-level changes that become relevant in the context of programmatic invocations, including (though not exclusively) integration with `dbt-server` + dbt Cloud.

This represents a first big step on a much longer journey, toward `dbt-core` as a mature & reliable software library. The initial set of functional APIs that we're aiming to include in v1.5 will be, by intention and necessity, a small subset of everything `dbt-core` is capable of doing today.

# Ready To implement
### New commands

These represent long-awaited functionality that we should expose as top-level commands, both in the CLI + API. They should be highly useful during programmatic invocations, and they provide parity with functionality that's been historically available in `dbt-rpc`.

- [x] https://github.com/dbt-labs/dbt-core/issues/6358
- [ ] https://github.com/dbt-labs/dbt-core/issues/6359

Follow-up:
- [ ] https://github.com/dbt-labs/dbt-core/issues/6526
- [ ] https://github.com/dbt-labs/dbt-core/issues/7156

### Changes to parsing

There is one fairly clear point of separation in `dbt-core` today: the end of parsing, and the beginning of execution. That remains an imperfect interface; this represents the work required to refactor & solidify it.

- [X] https://github.com/dbt-labs/dbt-core/issues/6357

### UX for programmatic invocations

We're talking about a _totally new_ way to invoke `dbt-core` (at least as the official ones go). Let's make sure that we have the requisite constructs, entry points, syntactic sugar, and documentation to support intermediate/advanced community members who want to start using it.

**This is an area where we're especially eager for feedback from the wider community!**

- [x] https://github.com/dbt-labs/dbt-core/issues/6381
- [x] https://github.com/dbt-labs/dbt-core/issues/6550

### Integration with `dbt-server`

Track ongoing `dbt-server` work items that are relevant to or enabled by changes in this epic.

- [x] https://github.com/dbt-labs/dbt-server/issues/127
- [x] https://github.com/dbt-labs/dbt-server/issues/128
- [ ] https://github.com/dbt-labs/dbt-core/issues/6763
- [ ] https://github.com/dbt-labs/dbt-core/issues/6878
- [ ] https://github.com/dbt-labs/dbt-core/issues/7070

# Current in refinement:
- [ ] #7093
- [ ] https://github.com/dbt-labs/dbt-core/issues/6547
- [ ] https://github.com/dbt-labs/dbt-core/issues/7104

### Need to create implementation ticket
- [x] https://github.com/dbt-labs/dbt-core/issues/6543

#### Spikes & investigations
- [ ] Triggering re-parses based on changes to env vars, `--vars`, credentials: https://github.com/dbt-labs/dbt-server/issues/128#issuecomment-1374916737
- [ ] De-globalizing adapters: https://github.com/dbt-labs/dbt-core/issues/5533#issuecomment-1252446282
### Lower-level changes

There are simplifying assumptions we can make about most `dbt-core` invocations: they have direct access to a terminal & file system, they're running one process at a time (zero concurrency), all steps take place in sequence, and it all happens in one OS/environment.

We don't anticipate these changes being relevant for most users who are interacting with `dbt-core`, whether via the CLI, or via scripting around its programmatic API. The current behavior will remain the sensible default. We still encourage any community members who are interested to weigh into any of these issues.

- [ ] https://github.com/dbt-labs/dbt-core/issues/6399
- [ ] https://github.com/dbt-labs/dbt-core/issues/6543
- [ ] https://github.com/dbt-labs/dbt-core/issues/6544
- [ ] https://github.com/dbt-labs/dbt-core/issues/6587 &rarr; https://github.com/dbt-labs/dbt-core/issues/6545
- [ ] https://github.com/dbt-labs/dbt-core/issues/6647

**Comment by jtcohen6** [comment]
Closing in favor of https://github.com/dbt-labs/dbt-core/issues/7162, which defines narrower scope of work to ship in v1.5
