### ISSUE TITLE
[CT-1636] [Tracking] v1.4.0b1 release

### ISSUE THREAD

**Issue by Fleid** [dbt-labs/dbt-core#6414]
### To-do
- [x] Release Core
- [x] Release Adapters
- [x] Release Cloud
- [x] Initialize docs: https://github.com/dbt-labs/docs.getdbt.com/issues/2427
- [x] Make progress on [v1.4-related docs changes](https://github.com/dbt-labs/docs.getdbt.com/labels/dbt-core%20v1.4)
- [x] Let the people know!

**Comment by jtcohen6** [comment]
@Fleid Just added a few related to docs :)

**Comment by Fleid** [comment]
🥷

**Comment by Fleid** [comment]
We'll re-build a more complete to-do list as we mature / evolve the release process.
