### ISSUE TITLE
[CT-1915] [Epic] Multi-project collaboration - Milestone 1

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#6747]
Develop new constructs that enable dbt developers to create, contract, and communicate data models like software APIs. This work should enable more scalable mono-repos, while also laying the foundation for Milestone 2.

Discussions:
- https://github.com/dbt-labs/dbt-core/discussions/6725
- https://github.com/dbt-labs/dbt-core/discussions/6726
- https://github.com/dbt-labs/dbt-core/discussions/6730
- https://github.com/dbt-labs/dbt-core/discussions/6736

```[tasklist]
## [Model contracts](https://github.com/dbt-labs/dbt-core/discussions/6726)

* [ ] https://github.com/dbt-labs/dbt-core/pull/6271
* [ ] https://github.com/dbt-labs/dbt-core/issues/6748
* [ ] https://github.com/dbt-labs/dbt-core/issues/6750
* [ ] https://github.com/dbt-labs/dbt-core/issues/7066
* [ ] https://github.com/dbt-labs/dbt-core/issues/7067
* [ ] https://github.com/dbt-labs/dbt-core/issues/6751
* [ ] https://github.com/dbt-labs/dbt-core/issues/6754
* [ ] https://github.com/dbt-labs/dbt-core/issues/6756
* [ ] https://github.com/dbt-labs/dbt-core/issues/7034
* [ ] https://github.com/dbt-labs/dbt-core/issues/6755
* [ ] https://github.com/dbt-labs/dbt-core/issues/7154
* [ ] https://github.com/dbt-labs/dbt-core/issues/6975
* [ ] https://github.com/dbt-labs/dbt-core/issues/7064
* [ ] https://github.com/dbt-labs/dbt-core/issues/7184
* [ ] https://github.com/dbt-labs/dbt-core/issues/7209
* [ ] https://github.com/dbt-labs/dbt-core/issues/7121
```

```[tasklist]
## Model contracts - Adapters
* [x] Introducing constraints and contract:
* [ ] https://github.com/dbt-labs/dbt-snowflake/pull/341
* [ ] https://github.com/dbt-labs/dbt-redshift/pull/229
* [ ] https://github.com/dbt-labs/dbt-bigquery/pull/426
* [ ] https://github.com/dbt-labs/dbt-spark/pull/574
* [x] Renaming constraints_enabled to contract:
* [ ] https://github.com/dbt-labs/dbt-snowflake/issues/479
* [ ] https://github.com/dbt-labs/dbt-bigquery/issues/548
* [ ] https://github.com/dbt-labs/dbt-spark/issues/645
* [ ] https://github.com/dbt-labs/dbt-redshift/issues/330
* [x] Implement get_column_schema_from_sql macro:
* [ ] https://github.com/dbt-labs/dbt-snowflake/issues/464 
* [ ] https://github.com/dbt-labs/dbt-bigquery/issues/529
* [ ] https://github.com/dbt-labs/dbt-spark/issues/639
* [ ] https://github.com/dbt-labs/dbt-redshift/issues/319
* [x] Enforcing model contracts in view materializations:
* [ ] https://github.com/dbt-labs/dbt-spark/issues/654
* [ ] https://github.com/dbt-labs/dbt-bigquery/issues/555
* [ ] https://github.com/dbt-labs/dbt-snowflake/issues/490
* [ ] https://github.com/dbt-labs/dbt-redshift/issues/340
* [x] Use unified constraints data structure:
* [ ] https://github.com/dbt-labs/dbt-snowflake/issues/491
* [ ] https://github.com/dbt-labs/dbt-bigquery/issues/567
* [ ] https://github.com/dbt-labs/dbt-redshift/issues/341
* [ ] https://github.com/dbt-labs/dbt-spark/issues/655
* [ ] constraint_support methods:
* [ ] https://github.com/dbt-labs/dbt-snowflake/issues/492
* [ ] https://github.com/dbt-labs/dbt-redshift/issues/342
* [ ] https://github.com/dbt-labs/dbt-bigquery/issues/568
* [ ] https://github.com/dbt-labs/dbt-spark/issues/656
* [ ] model-level constraints:
* [ ] https://github.com/dbt-labs/dbt-bigquery/issues/569
* [ ] https://github.com/dbt-labs/dbt-snowflake/issues/493
* [ ] https://github.com/dbt-labs/dbt-redshift/issues/343
* [ ] https://github.com/dbt-labs/dbt-spark/issues/657
* [x] Order-agnostic constraint ddl:
* [ ] https://github.com/dbt-labs/dbt-snowflake/issues/498
* [ ] https://github.com/dbt-labs/dbt-bigquery/issues/579
* [ ] https://github.com/dbt-labs/dbt-redshift/issues/356
* [ ] https://github.com/dbt-labs/dbt-spark/issues/671
* [x] Convert `contract` from bool to dictionary
* [ ] https://github.com/dbt-labs/dbt-bigquery/issues/633
* [ ] https://github.com/dbt-labs/dbt-snowflake/issues/539
* [ ] https://github.com/dbt-labs/dbt-redshift/issues/382
* [ ] https://github.com/dbt-labs/dbt-spark/issues/693
```

```[tasklist]
## [Model groups & access](https://github.com/dbt-labs/dbt-core/discussions/6730)
* [ ] https://github.com/dbt-labs/dbt-core/issues/6833
* [ ] https://github.com/dbt-labs/dbt-core/issues/6822
* [ ] https://github.com/dbt-labs/dbt-core/issues/6823
* [ ] https://github.com/dbt-labs/dbt-core/issues/6824
* [ ] https://github.com/dbt-labs/dbt-core/issues/6826
* [ ] https://github.com/dbt-labs/dbt-core/issues/6825
```

```[tasklist]
## [Model versions](https://github.com/dbt-labs/dbt-core/discussions/6736)
* [ ] https://github.com/dbt-labs/dbt-core/issues/7263
* [ ] https://github.com/dbt-labs/dbt-core/issues/6603
* [ ] https://github.com/dbt-labs/dbt-core/issues/7054
* [ ] https://github.com/dbt-labs/dbt-core/issues/6866
* [ ] https://github.com/dbt-labs/dbt-core/issues/6867
* [ ] https://github.com/dbt-labs/dbt-core/issues/6872
* [ ] https://github.com/dbt-labs/dbt-core/issues/6871
* [ ] https://github.com/dbt-labs/dbt-core/issues/6869
* [ ] https://github.com/dbt-labs/dbt-core/issues/7199
* [ ] https://github.com/dbt-labs/dbt-core/issues/7332
```

```[tasklist]
## dbt-docs Improvements
* [ ] https://github.com/dbt-labs/dbt-docs/issues/377
* [ ] dbt-labs/dbt-docs#381 
* [ ] dbt-labs/dbt-docs#378
* [ ] https://github.com/dbt-labs/dbt-docs/issues/379
* [ ] dbt-labs/dbt-docs#380 
* [ ] https://github.com/dbt-labs/dbt-docs/issues/406
* [ ] https://github.com/dbt-labs/dbt-docs/issues/405
```

```[tasklist]
## docs.getdbt.com
* [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/2839
* [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/2840
* [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/2841
* [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/2938
* [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/2945
* [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/3023
* [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/3099
```

```[tasklist]
## Tracking
* [ ] https://github.com/dbt-labs/dbt-core/issues/7170
* [ ] https://github.com/dbt-labs/dbt-core/issues/7171
```

```[tasklist]
## Moved to [milestone 2](https://github.com/dbt-labs/dbt-core/issues/7372)
- [ ] https://github.com/dbt-labs/dbt-core/issues/6984
- [ ] https://github.com/dbt-labs/dbt-core/issues/6868
- [ ] https://github.com/dbt-labs/dbt-core/issues/6870
- [ ] https://github.com/dbt-labs/dbt-core/issues/7063
- [ ] https://github.com/dbt-labs/dbt-core/issues/7227
- [ ] https://github.com/dbt-labs/dbt-core/issues/7226
- [ ] https://github.com/dbt-labs/dbt-core/issues/7065
```
