### ISSUE TITLE
[CT-1979] [Epic] Test Observability

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#6798]
```[tasklist]
### Coverage
- [ ] https://github.com/dbt-labs/dbt-core/issues/4809
- [ ] https://github.com/dbt-labs/dbt-core/issues/8272
```
```[tasklist]
### Reliability
- [ ] https://github.com/dbt-labs/dbt-core/issues/6836
- [ ] https://github.com/dbt-labs/dbt-core/issues/8081
```

```[tasklist]
### Performance
- [ ] https://github.com/dbt-labs/dbt-core/issues/6836
```
-----

### Stretch goals
```[tasklist]
### Low-hanging fruit / improvements
- [ ] #6354
- [ ] #6797
- [ ] https://github.com/dbt-labs/dbt-core/issues/8043
- [ ] https://github.com/dbt-labs/dbt-core/issues/6611
```
