### ISSUE TITLE
[CT-2024] 1.4.0 migration tracker for partner- and community-developed adapters

### ISSUE THREAD

**Issue by dataders** [dbt-labs/dbt-core#6849]
Using this as a status tracker on migration of adapter ecosystem to dbt-core.1.4.0. See #6624 for the main upgrade guide.

```[tasklist]
### Tasks
- [ ] https://github.com/ClickHouse/dbt-clickhouse/issues/135
- [ ] https://github.com/databricks/dbt-databricks/issues/267
- [ ] https://github.com/jwills/dbt-duckdb/issues/88
- [ ] https://github.com/tglunde/dbt-exasol/issues/57
- [ ] https://github.com/firebolt-db/dbt-firebolt/issues/93
- [ ] https://github.com/aws-samples/dbt-glue/issues/143
- [ ] https://github.com/markporoshin/dbt-greenplum/issues/14
- [ ] https://github.com/cloudera/dbt-hive/issues/94
- [ ] https://github.com/aurany/dbt-ibmdb2/issues/30
- [ ] https://github.com/cloudera/dbt-impala/issues/142
- [ ] https://github.com/iomete/dbt-iomete/issues/5
- [ ] https://github.com/MaterializeInc/materialize/issues/17500
- [ ] https://github.com/mindsdb/dbt-mindsdb/issues/18
- [ ] https://github.com/dbeatty10/dbt-mysql/issues/122
- [ ] https://github.com/chop-analytics/dbt-netezza/issues/18
- [ ] https://github.com/oracle/dbt-oracle/issues/70
- [ ] https://github.com/rockset/dbt-rockset/issues/28
- [ ] https://github.com/memsql/dbt-singlestore/issues/18
- [ ] https://github.com/dbt-labs/dbt-spark/issues/631
- [ ] https://github.com/dbt-msft/dbt-sqlserver/issues/333
- [ ] https://github.com/dbt-athena/dbt-athena/issues/136
- [ ] https://github.com/splitgraph/sgr/issues/773
- [ ] https://github.com/codeforkjeff/dbt-sqlite/issues/40
- [ ] https://github.com/StarRocks/dbt-starrocks/issues/15
- [ ] https://github.com/microsoft/dbt-synapse/issues/147
- [ ] https://github.com/Teradata/dbt-teradata/issues/63
- [ ] https://github.com/pingcap/dbt-tidb/issues/49
- [ ] https://github.com/starburstdata/dbt-trino/issues/223
- [ ] https://github.com/vertica/dbt-vertica/issues/67
- [ ] https://github.com/dremio/dbt-dremio/issues/117
- [ ] https://github.com/fal-ai/fal/issues/740
- [ ] https://github.com/databendcloud/dbt-databend/issues/1
- [ ] https://github.com/inferlabs/dbt-infer/issues/5
```

**Comment by dataders** [comment]
closing in favor of a comment in the discussion
https://github.com/dbt-labs/dbt-core/discussions/6624#discussioncomment-5663823
