### ISSUE TITLE
[CT-2301] [Epic] API-ification: outstanding tasks for v1.5

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#7162]
```[tasklist]
## Restoring previous behavior (P0)
- [ ] https://github.com/dbt-labs/dbt-core/issues/7010
- [ ] https://github.com/dbt-labs/dbt-core/issues/7118
- [ ] https://github.com/dbt-labs/dbt-core/issues/6097
- [ ] https://github.com/dbt-labs/dbt-core/issues/6098
- [ ] https://github.com/dbt-labs/dbt-core/issues/6913
- [ ] https://github.com/dbt-labs/dbt-core/issues/7206
```
```[tasklist]
## Unblocking dbt-server (P0)
- [ ] https://github.com/dbt-labs/dbt-core/issues/6359
- [ ] https://github.com/dbt-labs/dbt-core/issues/6763
- [ ] https://github.com/dbt-labs/dbt-core/issues/6878
- [ ] https://github.com/dbt-labs/dbt-core/issues/7070
- [ ] https://github.com/dbt-labs/dbt-core/issues/7207
- [ ] https://github.com/dbt-labs/dbt-core/issues/7197
```
```[tasklist]
### Perf & API cleanup (P1)
- [ ] https://github.com/dbt-labs/dbt-core/issues/6526
- [ ] https://github.com/dbt-labs/dbt-core/issues/6547
- [ ] https://github.com/dbt-labs/dbt-core/issues/7093
- [ ] https://github.com/dbt-labs/dbt-core/issues/6882
```
```[tasklist]
### UX improvements (P1)
- [ ] https://github.com/dbt-labs/dbt-core/issues/6546
```

**Comment by jtcohen6** [comment]
closing - all done :)
