### ISSUE TITLE
[CT-2386] [EPIC] Mature deployment: Retry & Slimmer CI

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#7301]
## Links
- [Internal one-pager](https://www.notion.so/dbtlabs/Mature-deployment-Retry-Slimmer-CI-03af4f23f651472b88ef2a5246f1f4a8)
- [Board view](https://github.com/orgs/dbt-labs/projects/22/views/56)

```[tasklist]
### Retry
- [ ] https://github.com/dbt-labs/dbt-core/issues/7299
- [ ] https://github.com/dbt-labs/dbt-core/issues/7302
- [ ] https://github.com/dbt-labs/dbt-core/issues/3600
- [ ] https://github.com/dbt-labs/dbt-core/issues/7448
- [ ] https://github.com/dbt-labs/dbt-core/issues/7502
- [ ] https://github.com/dbt-labs/dbt-core/issues/7607
- [ ] https://github.com/dbt-labs/dbt-core/issues/7753
- [ ] https://github.com/dbt-labs/dbt-core/issues/7785
```

```[tasklist]
### Slimmer CI & Clone
- [ ] https://github.com/dbt-labs/dbt-core/issues/7300
- [ ] https://github.com/dbt-labs/dbt-core/issues/7256
- [ ] https://github.com/dbt-labs/dbt-core/issues/7549
- [ ] https://github.com/dbt-labs/dbt-core/issues/7550
- [ ] https://github.com/dbt-labs/dbt-core/issues/7551
- [ ] https://github.com/dbt-labs/dbt-core/issues/7552

```

### Follow-ups
```[tasklist]
- [ ] https://github.com/dbt-labs/dbt-core/issues/7787
- [ ] https://github.com/dbt-labs/dbt-core/issues/7799
- [ ] https://github.com/dbt-labs/dbt-core/issues/7914
```

### Out of scope
- [ ] https://github.com/dbt-labs/dbt-core/issues/7387
