### ISSUE TITLE
[CT-2421] [Epic] Multi-project collaboration - Milestone 2

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#7372]
Discussions:
- https://github.com/dbt-labs/dbt-core/discussions/6725
- https://github.com/dbt-labs/dbt-core/discussions/6736

Docs epic:
- https://github.com/dbt-labs/docs.getdbt.com/issues/3362

```[tasklist]
## Cross-project refs
- [ ] https://github.com/dbt-labs/dbt-core/issues/7227
- [ ] https://github.com/dbt-labs/dbt-core/issues/7468
- [ ] https://github.com/dbt-labs/dbt-core/issues/7469
- [ ] https://github.com/dbt-labs/dbt-core/issues/7736
- [ ] https://github.com/dbt-labs/dbt-core/issues/7497
- [ ] https://github.com/dbt-labs/dbt-core/issues/7685
- [ ] https://github.com/dbt-labs/dbt-core/issues/7713
- [ ] https://github.com/dbt-labs/dbt-core/issues/7563
- [ ] https://github.com/dbt-labs/dbt-core/issues/7496
- [ ] https://github.com/dbt-labs/dbt-core/issues/7506
- [ ] https://github.com/dbt-labs/dbt-core/issues/7591
- [ ] https://github.com/dbt-labs/dbt-core/issues/7695
- [ ] https://github.com/dbt-labs/dbt-core/issues/7711
- [ ] https://github.com/dbt-labs/dbt-core/issues/7745
- [ ] https://github.com/dbt-labs/dbt-core/issues/7752
- [ ] https://github.com/dbt-labs/dbt-core/issues/7782
- [ ] https://github.com/dbt-labs/dbt-core/issues/7890
- [ ] https://github.com/dbt-labs/dbt-core/issues/7905
- [ ] https://github.com/dbt-labs/dbt-core/issues/7954
- [ ] https://github.com/dbt-labs/hubcap/issues/275
- [ ] https://github.com/dbt-labs/dbt-jsonschema/issues/81
```

```[tasklist]
## Package namespacing
- [ ] https://github.com/dbt-labs/dbt-core/issues/7446
- [ ] https://github.com/dbt-labs/dbt-core/issues/6705
- [ ] https://github.com/dbt-labs/dbt-core/issues/7444
```

```[tasklist]
## Model versioning & deprecation
* [ ] https://github.com/dbt-labs/dbt-core/issues/7433
* [ ] https://github.com/dbt-labs/dbt-core/issues/7443
* [ ] https://github.com/dbt-labs/dbt-core/issues/7487
* [ ] https://github.com/dbt-labs/dbt-core/issues/7639
* [ ] https://github.com/dbt-labs/dbt-core/issues/7704
* [ ] https://github.com/dbt-labs/dbt-core/issues/8039
```

```[tasklist]
## Model contracts: bugs, UX feedback, extensions
* [ ] https://github.com/dbt-labs/dbt-core/issues/7065
* [ ] https://github.com/dbt-labs/dbt-core/issues/7335
* [ ] https://github.com/dbt-labs/dbt-core/issues/7416
* [ ] https://github.com/dbt-labs/dbt-core/issues/7417
* [ ] https://github.com/dbt-labs/dbt-core/issues/7480
* [ ] https://github.com/dbt-labs/dbt-core/issues/7370
* [ ] https://github.com/dbt-labs/dbt-bigquery/issues/673
* [ ] https://github.com/dbt-labs/dbt-core/issues/7714
* [ ] https://github.com/dbt-labs/dbt-core/issues/7975
* [ ] https://github.com/dbt-labs/dbt-core/issues/7943
* [ ] https://github.com/dbt-labs/dbt-core/issues/8030
```

```[tasklist]
## Model access: UX feedback
- [ ] https://github.com/dbt-labs/dbt-core/issues/7226
```

```[tasklist]
## Tech debt
- [ ] https://github.com/dbt-labs/dbt-core/issues/7430
- [ ] https://github.com/dbt-labs/dbt-core/issues/7631
```

```[tasklist]
### 1.6 rc bugs & regressions
* [ ] https://github.com/dbt-labs/dbt-bigquery/issues/782
* [ ] https://github.com/dbt-labs/dbt-bigquery/issues/781
* [ ] https://github.com/dbt-labs/dbt-core/issues/8130
```

**Comment by MichelleArk** [comment]
Opened a [new epic for the next multi-project milestone](https://github.com/dbt-labs/dbt-core/issues/7979)) for any issues punted to future releases.
