### ISSUE TITLE
[CT-2520] [Epic] dbt-core 1.6 x MetricFlow Integration

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#7498]
For 1.6 our plan is to have a basic integration of [MetricFlow](https://github.com/dbt-labs/metricflow) with dbt-core for the semantic layer. What this integration looks like for dbt-core 1.6 is the following

- people will be able to define semantic layer objects in YAML files as defined in #7456
- core will parse these objects to the manifest as nodes
- core will output a new semantic manifest artifact
- adapters will allow for the optional installation of MetricFlow ~(i.e. `$ pip install dbt-snowflake[metricflow]`)~ (i.e. `$ pip install "dbt-metricflow[snowfalke]"`)
- querying will happen via the MetricFlow CLI for 1.6 (e.g. `$ mf query <metric_name> ...`

``` [tasklist]
### [P0] End-to-end
- [ ] https://github.com/dbt-labs/dbt-core/issues/7470
- [ ] https://github.com/dbt-labs/dbt-core/issues/7499
- [ ] https://github.com/dbt-labs/dbt-core/issues/7500
- [ ] https://github.com/dbt-labs/dbt-core/issues/7501
- [ ] https://github.com/dbt-labs/dbt-core/issues/7503
- [ ] https://github.com/dbt-labs/dbt-core/issues/7404
```

```[tasklist]
### \[P0/1] Follow-ups from end-to-end
- [ ] https://github.com/dbt-labs/dbt-core/issues/7800
- [ ] https://github.com/dbt-labs/dbt-core/issues/7820
- [ ] https://github.com/dbt-labs/dbt-core/issues/7821
- [ ] https://github.com/dbt-labs/dbt-core/issues/7822
- [ ] https://github.com/dbt-labs/dbt-core/issues/7823
- [ ] https://github.com/dbt-labs/dbt-core/issues/7827
- [ ] https://github.com/dbt-labs/dbt-core/issues/7833
- [ ] https://github.com/dbt-labs/dbt-core/issues/7853
- [ ] https://github.com/dbt-labs/dbt-core/issues/7864
- [ ] https://github.com/dbt-labs/dbt-core/issues/7865
- [ ] https://github.com/dbt-labs/dbt-core/issues/7866
- [ ] https://github.com/dbt-labs/dbt-core/issues/7884
- [ ] https://github.com/dbt-labs/dbt-core/issues/7897
- [ ] https://github.com/dbt-labs/dbt-core/issues/7898
- [ ] https://github.com/dbt-labs/dbt-core/issues/7907
- [ ] https://github.com/dbt-labs/dbt-core/issues/7938
- [ ] https://github.com/dbt-labs/dbt-core/issues/7854
- [ ] https://github.com/dbt-labs/dbt-core/issues/7969
- [ ] https://github.com/dbt-labs/dbt-core/issues/8064
- [ ] https://github.com/dbt-labs/dbt-core/issues/8065
- [ ] https://github.com/dbt-labs/dbt-core/issues/8077
```

```[tasklist]
### [P0] Migration support
- [ ] https://github.com/dbt-labs/dbt-core/issues/7507
```

```[tasklist]
### [P1] Adapters
- [ ] https://github.com/dbt-labs/dbt-core/issues/7839
```

**Comment by jtcohen6** [comment]
I opened a new epic for tracking the next milestone of work:
- https://github.com/dbt-labs/dbt-core/issues/8125
