### ISSUE TITLE
[CT-2638] Fix `--fail-fast` behavior

### ISSUE THREAD

**Issue by aranke** [dbt-labs/dbt-core#7785]
A/C:
1. Convert output of `--fail-fast` from single element to list
2. Inherit `--fail-fast` flag in `dbt retry` for consistency
3. Record skipped nodes in `run_results.json` (see https://github.com/dbt-labs/dbt-core/pull/7763#discussion_r1218248760, copied below)

> One thing that @MichelleArk noticed while investigating https://github.com/dbt-labs/dbt-core/issues/7744 (fix in https://github.com/dbt-labs/dbt-core/pull/7767): If a model is cancelled because of --fail-fast, its downstream dependencies will not be recorded as "skipped" in run_results.json, and so it won't be retried by dbt retry.
> (Repro case: model_a -> model_b (with error) -> model_c. dbt run -x && dbt retry. model_c never runs.)
> Would it make sense to address that here, or to open as a new/separate issue?
```[tasklist]
### Tasks
- [ ] Convert output of --fail-fast from single element to list
- [ ] Inherit --fail-fast flag in dbt retry for consistency
- [ ] Record skipped nodes in run_results.json (see Fixes #7299: dbt retry #7763 (comment), copied below)
```
