### ISSUE TITLE
[CT-2681] [Feature] Add `explain` or `dry_run` method to BaseAdapter

### ISSUE THREAD

**Issue by tlento** [dbt-labs/dbt-core#7839]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Sometimes we want to validate queries for syntactical or attribute reference errors without triggering the query run itself. For example, in the MetricFlow integration, we want to be able to run warehouse validations that do a simple metric query verification to ensure all metrics and expressions are defined using legal SQL expressions, but we do not want to trigger warehouse queries as that would be too costly.

For most SQL engines, this can be achieved by prefixing the query with the `EXPLAIN` keyword. Unfortunately, BigQuery does not support this - instead, callers have to pass in a flag to the BQ client at query time, which is not currently possible with the dbt-bigquery adapters. 

We propose adding a method to BaseAdapter that will allow end users to issue dry run/explain queries so callers - such as MetricFlow - can have a consistent interface for doing so regardless of the underlying engine being used in the dbt project.

Here's a suggested mock up of the API:

```
def dry_run(self, sql: str) -> None:
    """Trigger a dry run of a SQL query against the underlying engine. Useful for things like validating query syntax."""
    raise NotImplementedError
```

In the SQLAdapter we could default this method to prefix the input query with the `EXPLAIN` keyword, and then add an internal implementation in the BigQueryAdapter that works for that.

This method as described would either return None on success or throw an exception on failure. We could also return a result object here instead of requiring callers to try/catch every invocation manually.

Questions:

1. Are there better alternatives?
2. Do we want to call this `dry_run` or `explain`? The reasoning behind `dry_run` is explain might not return a useful plan output result.
3. Do we prefer to let a failure propagate as an exception, or handle the exception and return the errors along with some kind of response object? The former is more typical, the latter is more in line with how adapters manage calls to execute().
4. Should we make this an `@abstractmethod` on the BaseAdapter? That way downstream implementers know they have to add support for this if they are not extending SQLAdapter (or BigQueryAdapter). The drawback is once this goes live existing implementations will probably not work with that version of core.
5. Should we leave room for bind parameters in the function signature? Those appear to only be supported through the add_query() method today, which is not implemented for BigQuery.

### Are you interested in contributing this feature?

Yes, I will build this, I may need some guidance on test configuration.

```[tasklist]
### Tasks
- [ ] https://github.com/dbt-labs/dbt-snowflake/issues/682
- [ ] https://github.com/dbt-labs/dbt-redshift/issues/516
- [ ] https://github.com/dbt-labs/dbt-spark/issues/820
- [ ] https://github.com/dbt-labs/dbt-bigquery/issues/805
```

**Comment by jtcohen6** [comment]
@tlento Thanks for opening!

My answers to the questions (not to say these are the final answers):
1. Alternatives: We sometimes run queries with `where false limit 0`, but that's more to return the structure of the resulting dataset, and still heavier-weight than `explain` / real "dry run" if all we want is to validate SQL syntax.
2. I like the idea of calling this `dry_run`, if that's what we're really doing here.
3. Generally, dbt handles and wraps query failures as its own database/runtime exceptions. Then, rather than bubbling up the exception itself, we return a result object with `error` status.
4. I'd vote for making this _not_ an `@abstractmethod`, but rather a standard method on the `BaseAdapter` that (when called) raises a `NotImplementedError`. That way, we're not breaking things for existing adapter maintainers on upgrade to v1.6, unless they want to integrate with MetricFlow (and warehouse validations in particular) — or start using this method for other reasons.
5. We only use bind parameters for very specific query patterns — `insert` statements for seeds, I think — so I don't see an actual use case for baking that into the `dry_run` function signature.

**Comment by Almaz-KG** [comment]
Hey @tlento ! Happy to see this idea in git issue)

We've been working on dry-run feature for a while and have some results. Unfortunately, these results are not in a  sharable state, but I'll be happy to help you with our implementation details. 

Our tech stack is: 
- dbt-core <= 1.3.1 (rn migrating to 1.5.1)
- dbt-spark
- dbt-databricks

please, ping me if you are interested in collaborating. 
P.S. I'm a super newbie in dbt internal code-base, so my support will be mostly high-level and in guidance of how we did dry-run in our env

**Comment by Almaz-KG** [comment]
We made several attempts to implement dry-run, and two of them were successful. These implementations were integrated into your gitlab ci pipeline, so they usually are triggered by MR-open events. 

The first attempt was built on top of spark-sql `EXPLAIN` command. The idea was to do the following operations during dry-run process
1. `dbt compile`, which will generate ready to execute SQL files
2. and run `explain $sql_file_content`, and the result of this command can be used to understand whether the dbt model is valid or not. The `explain` command must be executed in prod metastore to be sure that the model validation is on top of actual metadata. 

This approach worked for us for a while, but afterward, we realized we want to get more advanced coverage in model validation. One of the main problems with this approach was that we can't track changes in a model structure. If a column has changed in the model, this dry-run will not work, because the database where the dry-run is executed does not yet have these model changes. (Keep in mind dry-run will run before changes will be merged into the main branch, so these changes are not in prod metastore yet)

The second attempt (which is currently running on our prod) is an almost complete emulation of prod env. Since we are working in Databricks, we can create spark clusters, with an ephemeral metastore (an in-memory metastore that lives only with the cluster, and when the cluster is destroyed, the metastore is also deleted). Therefore, when we create an MR, a databrickks spark-cluster (job cluster) is created, and the following commands are executed inside this cluster
- create schemas (raw, stg, prep, dwh, elementary, etc)
- shallow-clone parent models of MR's modified models (if needed)
- create source tables, seeds, snapshots, udfs, etc
- build $modified_in_mr_dbt_models
From the gitlab ci point, we run dry-run process only if MR has changes in dbt-models, and usually, the whole dry-run pipeline takes ~10 mins.

**Comment by tlento** [comment]
@Almaz-KG Thanks for the info, that's a great use case. This particular issue is focused on just the database connection aspect of the dry run scenario, and really would only be useful as a primitive for verifying a single incremental query change. As you know, doing something that can operate across the DAG requires additional mechanisms for dealing with propagating changes from upstream dependencies to downstream model queries. I'm not yet familiar enough with dbt itself to know what's possible today, but this seems like a good topic for a broader discussion.

I found [this discussion on unit testing SQL](https://github.com/dbt-labs/dbt-core/discussions/4455) in dbt, which is connected to this problem as well. That's more focused on running queries on dummy data, but I could imagine some amount of dry run execution being useful there as well, particularly for systems like spark and bigquery where setup and teardown can be quite slow in test clusters.

**Comment by tlento** [comment]
@jtcohen6 quick question on this:

> Generally, dbt handles and wraps query failures as its own database/runtime exceptions. Then, rather than bubbling up the exception itself, we return a result object with error status.

Do you have a pointer to where this gets converted from an error to an error status code?

From digging through the response handling logic it appears we either throw a DbtDatabaseError or a DbtRuntimeError. [Postgres](https://github.com/dbt-labs/dbt-core/blob/main/plugins/postgres/dbt/adapters/postgres/connections.py#L71-L96) and [Snowflake](https://github.com/dbt-labs/dbt-snowflake/blob/main/dbt/adapters/snowflake/connections.py#L269-L310) both implement the exception handler to raise, and the default SQLAdapter simply [wraps calls to add_query with that contextmanager](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/adapters/sql/connections.py#L67-L91) and [invokes add_query directly from execute](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/adapters/sql/connections.py#L143-L153).

The base adapter API simply wraps the connections.execute method by default, and that's as far as I've gotten.

Given this, I think I might just return None on success and let the exception happen otherwise. I can write documentation establishing that the expected contract is to raise one of the relevant custom exceptions, and add a test to enforce it. The issue with the test is if some adapter someplace *is* swallowing this exception inside of adapter.execute() it'll be tough to normalize.

If there is a standardized AdapterResponse instance with error suppression handled in a consistent way that'd be fine, I can then do whatever I need to on the MetricFlow side based on that response value.

**Comment by jtcohen6** [comment]
@tlento This is in `safe_run`, which is a building block used by most of our tasks:

https://github.com/dbt-labs/dbt-core/blob/fafab5d557d9c0e8daf336ef5c4fca9c2237925f/core/dbt/task/base.py#L381-L410

That method calls [`handle_exception`](https://github.com/dbt-labs/dbt-core/blob/fafab5d557d9c0e8daf336ef5c4fca9c2237925f/core/dbt/task/base.py#L371-L379) to handle the "catchable" database error, and then [`error_result`](https://github.com/dbt-labs/dbt-core/blob/fafab5d557d9c0e8daf336ef5c4fca9c2237925f/core/dbt/task/base.py#L272-L279) to convert the database error into a run result with "error" status.

So: This "catch-and-handle" logic lives inside the _task_, rather than the adapter method itself. I think it would be appropriate for a bad `dry_run` call to simply bubble up a `DatabaseError`, same as what would happen (I think) if you were to try running `EXPLAIN {invalid sql]` through `adapter.execute()`.

**Comment by jtcohen6** [comment]
Companion issues for adapters:
- https://github.com/dbt-labs/dbt-snowflake/issues/682
- https://github.com/dbt-labs/dbt-bigquery/issues/805
- https://github.com/dbt-labs/dbt-redshift/issues/516
- https://github.com/dbt-labs/dbt-spark/issues/820
