### ISSUE TITLE
[CT-2758] [Epic] Multi-project collaboration - Milestone 3

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#7979]
_We're still refining & prioritizing!_

Discussions:
- https://github.com/dbt-labs/dbt-core/discussions/6725

```[tasklist]
## Namespacing
- [ ] https://github.com/dbt-labs/dbt-core/issues/8327
```

```[tasklist]
## Contracts
- [ ] https://github.com/dbt-labs/dbt-core/issues/8070
- [ ] https://github.com/dbt-labs/dbt-core/issues/8697
- [ ] https://github.com/dbt-labs/dbt-docs/issues/433
- [ ] https://github.com/dbt-labs/dbt-core/issues/8183
- [ ] https://github.com/dbt-labs/dbt-core/issues/7432
- [ ] https://github.com/dbt-labs/dbt-core/issues/6984
- [ ] https://github.com/dbt-labs/dbt-core/issues/7759
- [ ] https://github.com/dbt-labs/dbt-core/issues/8007
- [ ] https://github.com/dbt-labs/dbt-core/issues/8022
- [ ] https://github.com/dbt-labs/dbt-core/issues/8282
- [ ] https://github.com/dbt-labs/dbt-core/issues/8062
- [ ] https://github.com/dbt-labs/dbt-core/issues/8266
- [ ] https://github.com/dbt-labs/dbt-core/issues/8028
- [ ] https://github.com/dbt-labs/dbt-core/issues/8384
- [ ] https://github.com/dbt-labs/dbt-core/issues/8827
```

```[tasklist]
## Versioning
- [ ] https://github.com/dbt-labs/dbt-core/issues/8126
- [ ] https://github.com/dbt-labs/dbt-core/issues/7442
- [ ] https://github.com/dbt-labs/dbt-core/issues/7688
- [ ] https://github.com/dbt-labs/dbt-core/issues/8189
- [ ] https://github.com/dbt-labs/dbt-core/issues/8540
```

```[tasklist]
## Groups & access
- [ ] https://github.com/dbt-labs/dbt-core/issues/7619
- [ ] https://github.com/dbt-labs/dbt-core/issues/8383
- [ ] https://github.com/dbt-labs/dbt-core/issues/8248
- [ ] https://github.com/dbt-labs/dbt-core/issues/8371
- [ ] https://github.com/dbt-labs/dbt-core/issues/7750
```

```[tasklist]
## Adapters
- [ ] https://github.com/dbt-labs/dbt-bigquery/issues/781
- [ ] https://github.com/dbt-labs/dbt-snowflake/issues/531
- [ ] https://github.com/dbt-labs/dbt-core/issues/8353
```
