### ISSUE TITLE
[CT-2831] [Epic] dbt-core 1.7 <> Semantic Layer

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#8125]
Follow-ups, extensions, UX improvements, and bugs sourced from:
- https://github.com/dbt-labs/dbt-core/discussions/7456
- https://github.com/dbt-labs/dbt-core/issues/7498
- [internal notion doc](https://www.notion.so/dbtlabs/dbt-Core-1-7-Semantic-Layer-Asks-4579bfe9abb6449eb0e5bbf32fab34f6)

```[tasklist]
### Features
- [ ] https://github.com/dbt-labs/dbt-core/issues/8593
- [ ] https://github.com/dbt-labs/dbt-core/issues/8594
- [ ] https://github.com/dbt-labs/dbt-core/issues/8595
```

```[tasklist]
### Bugs & consistency
- [ ] https://github.com/dbt-labs/dbt-core/issues/7934
- [ ] https://github.com/dbt-labs/dbt-core/issues/7968
- [ ] https://github.com/dbt-labs/dbt-docs/issues/431
- [ ] https://github.com/dbt-labs/dbt-core/issues/8511
- [ ] https://github.com/dbt-labs/dbt-core/issues/8509
- [ ] https://github.com/dbt-labs/dbt-core/issues/8546
- [ ] https://github.com/dbt-labs/dbt-core/issues/8609
```

```[tasklist]
### Ergonomics
- [ ] https://github.com/dbt-labs/dbt-core/issues/7504
- [ ] https://github.com/dbt-labs/dbt-core/issues/8172
- [ ] https://github.com/dbt-labs/dbt-core/issues/8319
```
```[tasklist]
### Tech Lag
- [ ] https://github.com/dbt-labs/dbt-core/issues/8134
- [ ] https://github.com/dbt-labs/dbt-core/issues/8135
- [ ] https://github.com/dbt-labs/dbt-core/issues/8136
- [ ] https://github.com/dbt-labs/dbt-core/issues/8139
- [ ] https://github.com/dbt-labs/dbt-core/issues/8140
- [ ] https://github.com/dbt-labs/dbt-core/issues/8141
- [ ] https://github.com/dbt-labs/dbt-core/issues/8142
```

```[tasklist]
### Documentation
- [ ] https://github.com/dbt-labs/dbt-core/issues/8513
- [ ] https://github.com/dbt-labs/dbt-core/issues/8514
```
