### ISSUE TITLE
[CT-2911] [Epic] Unit testing dbt models

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#8283]
See discussion #8275 

```[tasklist]
### \[P0]
- [ ] https://github.com/dbt-labs/dbt-core/issues/8289
- [ ] https://github.com/dbt-labs/dbt-core/issues/8757
- [ ] https://github.com/dbt-labs/dbt-core/issues/8287
- [ ] https://github.com/dbt-labs/dbt-core/issues/8294
- [ ] https://github.com/dbt-labs/dbt-core/issues/8295
- [ ] https://github.com/dbt-labs/dbt-core/issues/8296
- [ ] https://github.com/dbt-labs/dbt-core/issues/8421
- [ ] https://github.com/dbt-labs/dbt-core/issues/8512
- [ ] https://github.com/dbt-labs/dbt-core/issues/8626
- [ ] https://github.com/dbt-labs/dbt-core/issues/8290
- [ ] https://github.com/dbt-labs/dbt-core/issues/8422
- [ ] https://github.com/dbt-labs/dbt-core/issues/8698
- [ ] https://github.com/dbt-labs/dbt-core/issues/8651
- [ ] https://github.com/dbt-labs/dbt-core/issues/8517
- [ ] https://github.com/dbt-labs/dbt-core/issues/8558
- [ ] https://github.com/dbt-labs/dbt-core/issues/8507
- [ ] https://github.com/dbt-labs/dbt-core/issues/9053
- [ ] https://github.com/dbt-labs/dbt-core/issues/8652
- [ ] https://github.com/dbt-labs/dbt-core/issues/9052
- [ ] https://github.com/dbt-labs/dbt-core/issues/8285
- [ ] https://github.com/dbt-labs/dbt-core/issues/8699
- [ ] https://github.com/dbt-labs/dbt-core/issues/9067
- [ ] https://github.com/dbt-labs/dbt-core/issues/8979
- [ ] https://github.com/dbt-labs/dbt-core/issues/9128
- [ ] https://github.com/dbt-labs/dbt-core/issues/8799
- [ ] https://github.com/dbt-labs/dbt-core/issues/8944
- [ ] https://github.com/dbt-labs/dbt-core/issues/8508
- [ ] https://github.com/dbt-labs/dbt-core/issues/8606
```

```[tasklist]
### \[beta bugs done]
- [ ] https://github.com/dbt-labs/dbt-core/issues/9015
- [ ] https://github.com/dbt-labs/dbt-snowflake/issues/891
- [ ] https://github.com/dbt-labs/dbt-core/issues/9557
- [ ] https://github.com/dbt-labs/dbt-core/issues/9467
- [ ] https://github.com/dbt-labs/dbt-core/issues/9468
- [ ] https://github.com/dbt-labs/dbt-core/issues/9624
- [ ] https://github.com/dbt-labs/dbt-core/issues/9570
- [ ] https://github.com/dbt-labs/dbt-core/issues/9593
- [ ] https://github.com/dbt-labs/dbt-core/issues/9579
- [ ] https://github.com/dbt-labs/dbt-core/issues/9627
- [ ] https://github.com/dbt-labs/dbt-core/issues/9608
- [ ] https://github.com/dbt-labs/dbt-core/issues/9620
- [ ] https://github.com/dbt-labs/dbt-core/issues/9619
- [ ] https://github.com/dbt-labs/dbt-core/issues/9686
```
```[tasklist]
### \[beta bugs to do]
- [ ] https://github.com/dbt-labs/dbt-core/issues/9632
- [ ] https://github.com/dbt-labs/dbt-core/issues/9882
- [ ] https://github.com/dbt-labs/dbt-core/issues/9881
- [ ] https://github.com/dbt-labs/dbt-core/issues/9895
- [ ] https://github.com/dbt-labs/dbt-docs/issues/506
- [ ] https://github.com/dbt-labs/dbt-core/issues/10017
- [ ] https://github.com/dbt-labs/dbt-core/issues/9884
```
```[tasklist]
### \[P1]
- [ ] https://github.com/dbt-labs/dbt-core/issues/8649
- [ ] https://github.com/dbt-labs/dbt-core/issues/8980
- [ ] https://github.com/dbt-labs/dbt-core/issues/9344
- [ ] https://github.com/dbt-labs/dbt-core/issues/9179
- [ ] https://github.com/dbt-labs/dbt-core/issues/9237
- [ ] https://github.com/dbt-labs/dbt-docs/issues/472
- [ ] https://github.com/dbt-labs/dbt-core/issues/8423
- [ ] https://github.com/dbt-labs/dbt-core/issues/9405
- [ ] https://github.com/dbt-labs/dbt-core/issues/10053
- [ ] https://github.com/dbt-labs/dbt-core/issues/9280
- [ ] https://github.com/dbt-labs/dbt-core/issues/8708
- [ ] https://github.com/dbt-labs/dbt-core/issues/8664
- [ ] https://github.com/dbt-labs/dbt-core/issues/8499
- [ ] https://github.com/dbt-labs/dbt-core/issues/9282
- [ ] https://github.com/dbt-labs/dbt-adapters/issues/113
- [ ] https://github.com/dbt-labs/dbt-redshift/issues/726
- [ ] https://github.com/dbt-labs/dbt-postgres/issues/29
```
```[tasklist]
### \[P2]
- [ ] https://github.com/dbt-labs/dbt-core/issues/9220
- [ ] https://github.com/dbt-labs/dbt-core/issues/9109
- [ ] https://github.com/dbt-labs/dbt-core/issues/9283
- [ ] https://github.com/dbt-labs/dbt-core/issues/8981
- [ ] https://github.com/dbt-labs/dbt-core/issues/9238
- [ ] https://github.com/dbt-labs/dbt-core/issues/8292
- [ ] https://github.com/dbt-labs/dbt-core/issues/8293
- [ ] https://github.com/dbt-labs/dbt-core/issues/8425
- [ ] https://github.com/dbt-labs/dbt-core/issues/8291
```

**Comment by graciegoheen** [comment]
I'm going to close this as completed, since our first pass at unit testing was released in dbt-core `1.8`
