### ISSUE TITLE
[CT-2954] [Epic] Static Parsing Performance

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#8347]
```[tasklist]
- [ ] Revisit performance gains realized from dbt-extractor
- [ ] Build dbt-extractor on an ongoing basis
- [ ] Investigate avoiding jinja context (re)construction during parsing
- [ ] Investigate possibility of using jinja parser ast to get ref/source/config information
- [ ] https://github.com/dbt-labs/dbt-core/issues/8673
- [ ] https://github.com/dbt-labs/dbt-core/issues/8674
```
