### ISSUE TITLE
[CT-2955] Audit potential circular import dependencies

### ISSUE THREAD

**Issue by aranke** [dbt-labs/dbt-core#8349]
Follow-up from [INC-392](https://app.incident.io/dbt-labs/incidents/392)

```[tasklist]
### Tasks
- [x] Audit callers and callees of `utils.py` for circular dependencies, refactor if necessary
- [x] Audit callers and callees of `eventmgr.py` for circular dependencies, refactor if necessary
- [x] Audit callers and callees of `functions.py` for circular dependencies, refactor if necessary
- [x] Convert `import foo.bar` to `import bar from foo` wherever possible
- [ ] Potential stretch task: investigate tooling to audit these dependencies
- [ ] Potential stretch task # 2: automate said tooling from bullet above
```
