### ISSUE TITLE
[CT-3097] [Epic] CLI flexibility

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#8600]
```[tasklist]
### dbt-core changes
- [ ] https://github.com/dbt-labs/dbt-core/issues/8438
- [ ] https://github.com/dbt-labs/dbt-core/issues/8598
- [ ] https://github.com/dbt-labs/dbt-core/issues/8318
- [ ] https://github.com/dbt-labs/dbt-core/issues/6497
```

```[tasklist]
### docs.getdbt.com
- [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/4041
- [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/4040
```
