### ISSUE TITLE
[EPIC] Developer Platform Pilot

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#8706]
```[tasklist]
### Tasks
- [ ] Initial Setup (Start Free Trial, Invite users, assign admins, create teams)
- [ ] Connect GitHub App
- [ ] Connect Jira
- [ ] Accept services imported from GitHub
- [ ] Define Simple Service Maturity Matrix
- [ ] Run a Small Campaign
```
