### ISSUE TITLE
[CT-3158] [Developer Portal] Stretch Goal - Run a Small campaign

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#8714]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

OpsLevel allows you to run small campaigns to help get service health up.  What campaign we run is dependent on the state of our services after we get them set up.  As this is a pilot, it should be a small campaign to prove the process.

Some possibilities include:
    - dependabot PRs are less than 2 weeks old
    - Validate 'README.md' exists on all repos
    - Validate Branch Protections
    - Check for `CONTRIBUTING.md`, possibly check contents for standardization

### Acceptance criteria

1. Starting state of campaign has been recorded
2. Campaign is set up and run for 2 weeks
3. We can report on the changes in services in that time period

### Impact to Other Teams

adapters, sl, packages owners, 

These teams will need to put in a small amount of effort to complete the campaign

### Will backports be required?

no

### Context

Recording the improvements make in that time will be very important

```[tasklist]
### Tasks
- [ ] https://github.com/dbt-labs/adapters-team-private/issues/7
- [ ] https://github.com/dbt-labs/dbt-core/issues/9221
- [ ] https://github.com/dbt-labs/metricflow/issues/921
```
