### ISSUE TITLE
[CT-3270] [Epic] Decouple dbt/adapters from core

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#8917]
Discussion: https://github.com/dbt-labs/dbt-core/discussions/9171
Feature Branch: https://github.com/dbt-labs/dbt-core/pull/8906

```[tasklist]
### Cyclic dependencies
- [ ] https://github.com/dbt-labs/dbt-core/issues/8918
- [ ] https://github.com/dbt-labs/dbt-core/issues/8919
- [ ] https://github.com/dbt-labs/dbt-core/issues/8920
- [ ] https://github.com/dbt-labs/dbt-core/issues/8923
- [ ] https://github.com/dbt-labs/dbt-core/issues/8924
- [ ] https://github.com/dbt-labs/dbt-core/issues/9208
- [ ] https://github.com/dbt-labs/dbt-core/issues/8925
- [ ] https://github.com/dbt-labs/dbt-core/issues/9205
- [ ] https://github.com/dbt-labs/dbt-core/issues/9247
- [ ] https://github.com/dbt-labs/dbt-core/issues/8926
- [ ] https://github.com/dbt-labs/dbt-core/issues/8967
- [ ] https://github.com/dbt-labs/dbt-core/issues/9022
- [ ] https://github.com/dbt-labs/dbt-core/issues/9228
- [ ] https://github.com/dbt-labs/dbt-core/issues/9244
- [ ] https://github.com/dbt-labs/dbt-core/issues/9023
- [ ] https://github.com/dbt-labs/dbt-core/issues/9148
- [ ] https://github.com/dbt-labs/dbt-core/issues/8928
- [ ] https://github.com/dbt-labs/dbt-core/issues/8927
- [ ] https://github.com/dbt-labs/dbt-core/issues/8969
- [ ] https://github.com/dbt-labs/dbt-core/issues/9024
- [ ] https://github.com/dbt-labs/dbt-core/issues/9214
- [ ] https://github.com/dbt-labs/dbt-core/issues/9215
- [ ] https://github.com/dbt-labs/dbt-core/issues/9217
- [ ] https://github.com/dbt-labs/dbt-core/issues/9218
- [ ] https://github.com/dbt-labs/dbt-core/issues/9249
- [ ] https://github.com/dbt-labs/dbt-core/issues/9250
- [ ] https://github.com/dbt-labs/dbt-core/issues/9292
- [ ] https://github.com/dbt-labs/dbt-core/issues/9293
- [ ] https://github.com/dbt-labs/dbt-core/issues/9332
- [ ] https://github.com/dbt-labs/dbt-core/issues/9334
- [ ] https://github.com/dbt-labs/dbt-core/issues/9337
- [ ] https://github.com/dbt-labs/dbt-core/issues/9362
```
```[tasklist]
### Refactors
- [ ] https://github.com/dbt-labs/dbt-core/issues/9025
- [ ] https://github.com/dbt-labs/dbt-core/issues/9150
- [ ] https://github.com/dbt-labs/dbt-core/issues/9151
- [ ] https://github.com/dbt-labs/dbt-core/issues/9152
- [ ] https://github.com/dbt-labs/dbt-common/issues/80
```

```[tasklist]
### 1P Adapter Migrations
- [ ] https://github.com/dbt-labs/dbt-core/issues/9190
- [ ] https://github.com/dbt-labs/dbt-core/issues/9186
- [ ] https://github.com/dbt-labs/dbt-core/issues/9187
- [ ] https://github.com/dbt-labs/dbt-core/issues/9188
- [ ] https://github.com/dbt-labs/dbt-core/issues/9189
- [x] Migrate dbt-postgres for feature/decouple-adapters-from-core
```
```[tasklist]
### 3P Adapter Migrations
- [ ] https://github.com/dbt-labs/dbt-core/issues/9766
```
