### ISSUE TITLE
[CT-3394] [Epic] Stabilize External Interfaces

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#9099]
### Description 

```[tasklist]
# Adapters
- [ ] https://github.com/dbt-labs/dbt-core/issues/8917
- [ ] https://github.com/dbt-labs/dbt-common/issues/4
- [ ] https://github.com/dbt-labs/dbt-adapter/issues/2
```
```[tasklist]
# Flags for Behaviour Changes
- [ ] https://github.com/dbt-labs/dbt-core/issues/9183
- [ ] https://github.com/dbt-labs/dbt-core/issues/5609
- [ ] https://github.com/dbt-labs/dbt-core/issues/9518
```
```[tasklist]
### Artifacts
- [ ] https://github.com/dbt-labs/dbt-core/issues/9193
- [ ] https://github.com/dbt-labs/dbt-core/issues/9613
- [ ] https://github.com/dbt-labs/dbt-core/issues/9200
- [ ] https://github.com/dbt-labs/dbt-core/issues/9385
- [ ] https://github.com/dbt-labs/dbt-core/issues/9378
- [ ] https://github.com/dbt-labs/dbt-core/issues/9379
- [ ] https://github.com/dbt-labs/dbt-core/issues/9380
- [ ] https://github.com/dbt-labs/dbt-core/issues/9381
- [ ] https://github.com/dbt-labs/dbt-core/issues/9382
- [ ] https://github.com/dbt-labs/dbt-core/issues/9384
- [ ] https://github.com/dbt-labs/dbt-core/issues/9383
- [ ] https://github.com/dbt-labs/dbt-core/issues/9386
- [ ] https://github.com/dbt-labs/dbt-core/issues/9387
- [ ] https://github.com/dbt-labs/dbt-core/issues/9388
- [ ] https://github.com/dbt-labs/dbt-core/issues/9390
- [ ] https://github.com/dbt-labs/dbt-core/issues/9438
- [ ] https://github.com/dbt-labs/dbt-core/issues/9615
- [ ] https://github.com/dbt-labs/dbt-core/issues/9567
- [x] https://github.com/dbt-labs/dbt-core/issues/9667
- [x] Remove attributes from BaseNode once all subclasses inherit from resource class
- [x] Reorganize tests/functional/artifacts
- [ ] https://github.com/dbt-labs/dbt-core/issues/7802
```

```[tasklist]
### Refactors
- [ ] https://github.com/dbt-labs/dbt-core/issues/8027
- [ ] https://github.com/dbt-labs/dbt-core/issues/9926
- [ ] https://github.com/dbt-labs/dbt-core/issues/7157
```
