### ISSUE TITLE
[CT-3404] [EPIC] dbt-core 1.8 x Semantic Layer

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#9116]
```[tasklist]
### Must Haves
- [ ] https://github.com/dbt-labs/dbt-core/issues/9117
- [ ] https://github.com/dbt-labs/dbt-core/issues/9203
- [ ] https://github.com/dbt-labs/dbt-core/issues/9540
- [ ] https://github.com/dbt-labs/dbt-core/issues/9441
- [ ] https://github.com/dbt-labs/dbt-core/issues/8860
```
---

```[tasklist]
### Nice To Have
- [ ] https://github.com/dbt-labs/dbt-core/issues/8880
```

---

Likely needs backporting to `1.7.latest`:

```[tasklist]
### Saved queries: UX improvements
- [ ] https://github.com/dbt-labs/dbt-core/issues/9532
- [ ] https://github.com/dbt-labs/dbt-core/issues/9533
- [ ] https://github.com/dbt-labs/dbt-core/issues/9534
- [ ] https://github.com/dbt-labs/dbt-core/issues/9360
- [ ] https://github.com/dbt-labs/dbt-core/issues/9629
```
