### ISSUE TITLE
[Epic] Streamline Incremental Strategies

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#9290]
This epic comprises the changes to Core + Adapters necessary to streamline incremental strategies as described in https://github.com/dbt-labs/dbt-core/issues/5245.

```[tasklist]
### Core
- [ ] https://github.com/dbt-labs/dbt-core/issues/5245
```

```[tasklist]
### Adapters
- [ ] https://github.com/dbt-labs/dbt-snowflake/issues/195
- [ ] https://github.com/dbt-labs/dbt-bigquery/issues/232
- [ ] https://github.com/dbt-labs/dbt-bigquery/issues/242
- [ ] https://github.com/dbt-labs/dbt-spark/issues/402
- [ ] https://github.com/dbt-labs/dbt-spark/issues/411
- [ ] dbt-redshift
```

```[tasklist]
### Documentation
- [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/1761
```
