### ISSUE TITLE
[Epic] Applied State (part 2)

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#9425]
This epic comprises the remaining work on the [Applied State initiative](https://github.com/dbt-labs/dbt-core/issues/8316) to support better visibility into the current state of the database in a more performant way.

```[tasklist]
### dbt-core 1.8
- [ ] https://github.com/dbt-labs/dbt-core/issues/9078
- [ ] https://github.com/dbt-labs/dbt-core/issues/8705
- [ ] https://github.com/dbt-labs/dbt-core/issues/9666
- [ ] https://github.com/dbt-labs/dbt-core/issues/9320
```
```[tasklist]
### next
- [ ] https://github.com/dbt-labs/dbt-core/issues/9506
- [ ] https://github.com/dbt-labs/dbt-core/issues/9979
```

**Comment by adamcunnington-mlg** [comment]
@graciegoheen / @MichelleArk sorry for the direct Q on this but struggling to understand from docs / issue / PRs. Has the support for batch metadata collection been added for BQ specifically? I saw the general work in dbt-adapters and snowflake and redshift specific but I don't think BQ? Thank you

**Comment by jtcohen6** [comment]
@adamcunnington-mlg I believe so, yes:
- https://github.com/dbt-labs/dbt-bigquery/pull/1060

**Comment by adamcunnington-mlg** [comment]
@jtcohen6 I think that is just the initial support and not the batch-route - which is the critical bit. Please advise - many thanks

**Comment by MichelleArk** [comment]
Hey @adamcunnington-mlg -- I've summarized some [spiking done](https://github.com/dbt-labs/dbt-bigquery/pull/1232) to evaluate the cost/benefit of implementing a batch-route for metadata freshness in BigQuery here: https://github.com/dbt-labs/dbt-bigquery/issues/938. There are more details in the spike report, but my overall conclusion is that there isn't currently a way to implement a batch-strategy that achieves performance improvements for metadata-based source freshness given limitations of BigQuery's Python SDK.

**Comment by adamcunnington-mlg** [comment]
@MichelleArk I believe this is a missed conclusion here. I've left some details against your more comprehensive response; https://github.com/dbt-labs/dbt-bigquery/issues/938#issuecomment-2108070256

These details are also in the original FR; https://github.com/dbt-labs/dbt-core/issues/7012#issuecomment-1468182875

**Comment by graciegoheen** [comment]
I'm going to close this issue out since it was for our 1.8 release

**Comment by graciegoheen** [comment]
Hi @adamcunnington-mlg - that is correct, it is still not implemented. 

@jtcohen6 left a response back in the issue in dbt-bigquery back in May (see [here](https://github.com/dbt-labs/dbt-bigquery/issues/938#issuecomment-2109531126)):

> If you could provide us with concrete numbers for both approaches, that would help me a lot in deciding on the appropriate next step here — to switch this behavior for everyone (strictly better), to consider implementing it as another configurable option (with both pros & cons relative to the v1.8 behavior), or to put it down for good ("do nothing").

This is not a top priority for us atm, but would be helpful to understand the difference in performance between these approaches to decide on the appropriate next step.

**Comment by graciegoheen** [comment]
Ah! @adamcunnington-mlg I see you follow up in [this issue](https://github.com/dbt-labs/dbt-bigquery/issues/1239#issuecomment-2154410674). 

The implementation has been de-risked, so there's nothing blocking this work. This is not a focus for our team right now, but we would definitely review a PR for it if someone from the community wanted to open one up :)
