### ISSUE TITLE
[Epic] Robust Testing Initiative

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#9649]
```[tasklist]
### Fixture Building+ Major Examples
- [ ] https://github.com/dbt-labs/dbt-core/issues/9665
- [ ] https://github.com/dbt-labs/dbt-core/issues/9870
- [ ] https://github.com/dbt-labs/dbt-core/issues/9984
- [ ] https://github.com/dbt-labs/dbt-core/issues/9983
- [ ] https://github.com/dbt-labs/dbt-core/issues/9865
- [ ] https://github.com/dbt-labs/dbt-core/issues/9866
- [ ] https://github.com/dbt-labs/dbt-core/issues/9947
- [ ] https://github.com/dbt-labs/dbt-core/issues/9867
- [ ] https://github.com/dbt-labs/dbt-core/issues/8627
- [ ] https://github.com/dbt-labs/dbt-core/issues/10000
- [ ] https://github.com/dbt-labs/dbt-core/issues/10001
- [ ] https://github.com/dbt-labs/dbt-core/issues/9868
- [ ] Schedule bash for team to try and convert indivual tests
```

```[tasklist]
### Happy Path Functional Testing
- [ ] https://github.com/dbt-labs/dbt-core/issues/10256
- [ ] https://github.com/dbt-labs/dbt-core/issues/10257
- [ ] https://github.com/dbt-labs/dbt-core/issues/10286
- [ ] https://github.com/dbt-labs/dbt-core/issues/10288
- [ ] https://github.com/dbt-labs/dbt-core/issues/10330
```

```[tasklist]
### Parameterized Tests
- [ ] https://github.com/dbt-labs/dbt-core/issues/10181
- [ ] https://github.com/dbt-labs/dbt-core/issues/10287
- [ ] https://github.com/dbt-labs/dbt-core/issues/10328
- [ ] https://github.com/dbt-labs/dbt-core/issues/10331
```

```[tasklist]
### Test Organization
- [ ] https://github.com/dbt-labs/dbt-core/issues/9961
```

```[tasklist]
### TODO
- [ ] https://github.com/dbt-labs/dbt-core/issues/9871
- [ ] https://github.com/dbt-labs/dbt-core/issues/9872
- [ ] https://github.com/dbt-labs/dbt-core/issues/9885
- [ ] [refactor] Seperate selection method to make it easier to test
- [ ] Identify functional tests that should be unittest and write guidance
- [ ] [SPIKE] Can we use codecoverage to protect feature sets
- [ ] https://github.com/dbt-labs/dbt-core/issues/10145
- [ ] https://github.com/dbt-labs/dbt-core/issues/10329
```
