### ISSUE TITLE
[Epic] Cross-database `cast` macro

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#9976]
This epic comprises the changes across dbt Labs repos necessary to implement a cross-database `cast` macro  as described in https://github.com/dbt-labs/dbt-adapters/issues/84.

### Implementation

The `cast` function is specified in ISO/IEC 9075-2 (part 2 of the SQL standard), so there is a natural adapter-agnostic implementation:
```sql
cast({{ expression }} as {{ data_type }})
```

### Utility

It can be useful for end-users when they are looking for an adapter-agnostic method to `cast` a SQL expression to a specific data type.

Having a cross-database `cast` macro has been suggested as a way to address a variety of things including, but not limited to:
- https://github.com/dbt-labs/dbt-adapters/pull/55
- https://github.com/dbt-labs/dbt-adapters/pull/165
- https://github.com/dbt-labs/dbt-snowflake/pull/969
- https://github.com/dbt-labs/dbt-core/issues/5445#issuecomment-1210875104

For example, it can be useful in implementations of `safe_cast` (falling back to `cast` for types that don't support a try / safe cast, e.g. in [snowflake](https://github.com/dbt-labs/dbt-snowflake/pull/896/files#diff-d430faaa1899044a611162c84d921ec87857e6febcd79d9792680df8b96dfd57R11)). 

```[tasklist]
### dbt-adapters
- [ ] https://github.com/dbt-labs/dbt-adapters/pull/55
- [ ] https://github.com/dbt-labs/dbt-adapters/issues/84
- [ ] https://github.com/dbt-labs/dbt-adapters/pull/173
```

```[tasklist]
### dbt-postgres
- [ ] https://github.com/dbt-labs/dbt-postgres/issues/76
- [ ] https://github.com/dbt-labs/dbt-postgres/pull/77
```

```[tasklist]
### dbt-redshift
- [ ] https://github.com/dbt-labs/dbt-redshift/issues/804
- [ ] https://github.com/dbt-labs/dbt-redshift/pull/805
```

```[tasklist]
### dbt-snowflake
- [ ] https://github.com/dbt-labs/dbt-snowflake/pull/896
- [ ] https://github.com/dbt-labs/dbt-snowflake/issues/1009
- [ ] https://github.com/dbt-labs/dbt-snowflake/pull/1010
```

```[tasklist]
### dbt-bigquery
- [ ] https://github.com/dbt-labs/dbt-bigquery/issues/1214
- [ ] https://github.com/dbt-labs/dbt-bigquery/pull/1215
```

```[tasklist]
### dbt-spark
- [ ] https://github.com/dbt-labs/dbt-spark/issues/1028
- [ ] https://github.com/dbt-labs/dbt-spark/pull/1029
```

```[tasklist]
### Documentation
- [ ] https://github.com/dbt-labs/docs.getdbt.com/pull/5278
- [ ] Include in migration guide for adapter maintainers
```
